#! /bin/sh
### BEGIN INIT INFO
# Provides:	  Firewall
# Required-Start: $network
# Required-Stop:  $network
# Should-Start:
# Should-Stop:
# Default-Start:  3 5
# Default-Stop:   0 1 2 6
# Short-Description: Loads and unloads firewall settings
# Description:
### END INIT INFO

#First reset status of this service
#	/etc/rc.status
#rc_reset

# set default option
FWSTART="/home/fw_start"
if [ ! -f ${FWSTART} ]; then
   echo -n "Plik konfiguracyjny start nie istnieje. \n"
#   rc_status -s
   exit 6
fi
FWSTOP="/home/fw_stop"
if [ ! -f ${FWSTOP} ]; then
   echo -n "Plik konfiguracyjny stop nie istnieje. \n"
#   rc_status -s
   exit 6
fi

case "$1" in
   start)
	echo -n "Starting firewall \n"
	iptables-restore <$FWSTART
	#rc_status -v
   ;;
   stop)
	echo -n "Shutting down firewall \n"
        iptables-restore <$FWSTOP
        #rc_status -v
   ;;
   restart)
	$0 stop
	$0 start
	#rc_status
   ;;
   status)
	echo -n "Obecna konfiguracja \n"
	iptables -L
	#rc_status -v
   ;;
   *)
	echo "Uzyj: $0 {start|stop|status|restart} \n"
	exit 1
   ;;
esac
#rc_exit


